### ISSUE TITLE
TypeError at /admin/campaign/subscriberlist/ when creating a SubscriberList

### ISSUE THREAD

**Issue by antonioagostino** [arneb/django-campaign#26]
I tried to create a SubscriberList form the Django Admin Interface with the following parameters

- Content Type: "auth | user"
- Filter Condition: "{"is_active": true}"
- Email-Field name: email

But it gives me this error:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/campaign/subscriberlist/

Django Version: 3.2.7
Python Version: 3.9.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'campaign']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1815, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/db/models/query.py", line 68, in __iter__
    for row in compiler.results_iter(results):
  File "/Users/antoninoagostino/.local/share/virtualenvs/DjangoCampaignManager-jNwuWTWe/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1122, in apply_converters
    value = converter(value, expression, connection)

Exception Type: TypeError at /admin/campaign/subscriberlist/
Exception Value: from_db_value() missing 1 required positional argument: 'context'

```

**Comment by arneb** [comment]
Looks like a bug. I will try to fix it.

**Comment by rjbishop** [comment]
Hey still having trouble with the  create a SubscriberList form in the Django Admin Interface with the following parameters


- Content Type: "auth | user"
- Filter Condition: "{"is_active": true}"
- Email-Field name: email


But it gives me this error:
'NoneType' object has no attribute 'items'

Environment:


Request Method: POST
Request URL: http://localhost:8000/admin/campaign/subscriberlist/add/

Django Version: 3.2.11
Python Version: 3.9.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'campaign',
 'emailmarketing']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\contrib\admin\options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\contrib\admin\options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\contrib\admin\options.py", line 1579, in _changeform_view
    form_validated = form.is_valid()
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\forms\forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\forms\forms.py", line 170, in errors
    self.full_clean()
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\forms\forms.py", line 373, in full_clean
    self._clean_form()
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\django\forms\forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "C:\Users\me123\Documents\projects\my_project\venv\lib\site-packages\campaign\forms.py", line 40, in clean
    Model._default_manager.filter(**{str(k): v for k, v in filter_condition.items()})

Exception Type: AttributeError at /admin/campaign/subscriberlist/add/
Exception Value: 'NoneType' object has no attribute 'items'

It appears like self.cleaned_data.get("filter_condition") is returning None
